# -*- coding: utf-8 -*-
"""Introdução a Machine Learning e Classificação com SKLearn - 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfSI-3UJklU6OVo4Vkb8bPZ3A_ofgHHD
"""

#features(1 sim, 0 não)
#pelo é longo?
#perna é curta?
#emite latidos?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# 1 == porco, 0 == cachorro
train_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
train_y= [1, 1, 1, 0, 0, 0] # labels

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(train_x, train_y)

animal_misterioso = [1, 1, 1]
model.predict([animal_misterioso])

misterioso1 = [1, 1, 1]
misterioso2 = [1, 1, 0]
misterioso3 = [0, 1, 1]

test_y = [0, 1, 1]
test_x = [misterioso1, misterioso2, misterioso3]

previsoes = model.predict(test_x)

previsoes == test_y

corretos = (previsoes == test_y).sum()
total = len(test_x)
taxa_de_acerto = corretos/total
print(f'Taxa de acerto: {taxa_de_acerto*100:.2f}')

from sklearn.metrics import accuracy_score


taxa_de_acerto = accuracy_score(test_y, previsoes)
print(f'Taxa de acerto: {taxa_de_acerto*100:.2f}')

